version: "3"
services:
  combined_container:
    build:
      context: .
    ports:
      - "8082:8080"
      - "3307:3306"
    volumes:
      - mysql2_data:/var/lib/mysql
      - app2_data:/usr/local/tomcat/webapps

volumes:
  mysql2_data:
  app2_data:
