version: "3"
services:
  combined_container:
    build:
      context: .
    ports:
      - "8082:8080"
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - app_data:/usr/local/tomcat/webapps

volumes:
  mysql_data:
  app_data:
